name: Run Tests

on:
  push:
    branches: ["main"]
    paths-ignore:
      - "**.md"
      - "**.example"
  pull_request:
    branches: ["main"]
    paths-ignore:
      - "**.md"
      - "**.example"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mssql:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          SA_PASSWORD: ${{ secrets.SQL_SA_PASSWORD }}
          ACCEPT_EULA: "Y"
        ports:
          - 1433:1433

    env:
      CONNECTIONSTRINGS__TESTDATABASE: Server=localhost;Database=SocialMedia;User=sa;Password=${{ secrets.SQL_SA_PASSWORD }};TrustServerCertificate=True;MultipleActiveResultSets=true;

    steps:
      - uses: actions/checkout@v3

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7.x"

      - name: Run bootstrap script
        run: ./scripts/bootstrap.sh -ci

      - name: Run build script
        run: ./scripts/build.sh --configuration Release

      - name: Run test script
        run: ./scripts/test.sh --configuration Release --nobuild
